const { chromium } = require('playwright');
const SP='/tmp/claude-0/-home-user-hpc-topology-viewer/a1c7fe8d-5ec1-5239-a2b2-8be8b10295fa/scratchpad';
(async () => {
  const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
  const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
  const errs=[]; p.on('pageerror', e=>errs.push(e.message));
  p.on('console', m=>{ if(m.type()==='error' && !/favicon/.test(m.text())) errs.push('c: '+m.text()); });
  await p.goto('http://localhost:3000/parallel-topology/demo.html', {waitUntil:'networkidle'});
  await p.waitForTimeout(1000);
  await p.click('button[data-v="chain"]'); await p.waitForTimeout(1200);
  await p.click('button[data-tab="side"]'); await p.waitForTimeout(2500);
  await p.screenshot({ path: SP+'/D1-side.png' });
  await p.click('button[data-tab="front"]'); await p.waitForTimeout(2000);
  await p.screenshot({ path: SP+'/D2-front.png' });
  await p.click('button[data-tab="3d"]'); await p.waitForTimeout(1200);
  await p.screenshot({ path: SP+'/D3-3d.png' });
  if(errs.length) console.log('ERRORS:', errs.slice(0,6));
  else console.log('console 干净');
  await b.close();
})();
