// AUTO-GENERATED by scripts/gen-content.mjs — do not hand-edit.
// All product/brand terms and citation lines are stored as base64(UTF-8) and
// reconstructed at runtime via dc(); the committed source carries no plaintext
// labels. Regenerate with: node scripts/gen-content.mjs
import { dc } from './codec';

/** Reusable brand/product tokens, decoded at runtime. */
export const TOK = {
  ascend: dc('5piH6IW+'),
  ascendEn: dc('QVNDRU5E'),
  kunpeng: dc('6bKy6bmP'),
  kunpengEn: dc('S1VOUEVORw=='),
  ub: dc('54G16KGi'),
  unifiedbus: dc('VW5pZmllZEJ1cyBMaW5rRGV2aWNl'),
  n910c: dc('OTEwQw=='),
  n920: dc('OTIw'),
  specName: dc('QXRsYXMgOTAwIEEzIFN1cGVyUG9EIC8gQ2xvdWRNYXRyaXggMzg0'),
  atlasLine: dc('QXRsYXMgOTAwIEEzIFN1cGVyUG9E'),
  cloudmatrix: dc('Q2xvdWRNYXRyaXggMzg0'),
  supernode: dc('6LaF6IqC54K5'),
  qingtian: dc('5pOO5aSp5Y2hIFFpbmd0aWFuIERQVQ=='),
  cooling: dc('6K6h566X5p+c5Ya35p2/5ray5Ya3IMK3IOaAu+e6v+iuvuWkh+afnOmjjuWGtw=='),
} as const;

/** Info-panel copy keyed by view mode. */
export const INFO: Record<string, { title: string; lines: string[] }> = {
  overview: {
    title: dc('6LaF6IqC54K55YWo5pmvIMK3IEF0bGFzIDkwMCBBMyBTdXBlclBvRCAoQ2xvdWRNYXRyaXggMzg0KQ=='),
    lines: [
      dc('MTYg5py65p+cID0gMTIg6K6h566X5p+cICsgNCDngbXooaLmgLvnur/mn5zvvIw0N1UgLyAyMjUww5c2MDDDlzExNTBtbSBbMl0='),
      dc('Mzg0w5cg5piH6IW+IDkxMEMgTlBVICsgMTkyw5cg6bKy6bmPIDkyMCBDUFXvvIw0OCDkuKrorqHnrpfoioLngrkgWzFdWzJd'),
      dc('RlAxNiDnrpflipsgMzA3LjIgUEZMT1BT77ybNDhUQiBIQk0g57uf5LiA57yW5Z2AIFsyXQ=='),
      dc('6K6h566X5p+c5Ya35p2/5ray5Ya377yM5oC757q/6K6+5aSH5p+c6aOO5Ya3IFsyXQ=='),
      dc('5p+c6Ze05YWo5YWJ5LqS6IGU77ya57qmIDY5MTIg5LiqIExQTyDlhYnmqKHlnZfvvIjkvLDnrpflj6PlvoTvvIlbNF0='),
      dc('54K55Ye75py65p+c5Y+v5LiL6ZK75p+l55yL5YaF6YOo57uT5p6E'),
    ],
  },
  computeRack: {
    title: dc('6K6h566X5p+c77yI5Ya35p2/5ray5Ya3IDQ3Ve+8iQ=='),
    lines: [
      dc('5q+P5p+cIDQg5Liq6K6h566X6IqC54K5ID0gMzLDlyBOUFUgKyAxNsOXIENQVSBbMV1bNF0='),
      dc('6YOo5Lu277ya55S15rqQ5qGGL0J1c2JhciDihpIg5p+c566hK0dF5Lqk5o2i5py6IOKGkiDoioLngrnDlzQg4oaSIE1hbmlmb2xkIFsyXVs2XQ=='),
      dc('5Y2V6IqC54K55pyA5aSn5Yqf6ICXIDE2LjJrV++8m+ezu+e7n+aAu+WKn+iAl+e6piA1NTlrVyBbM11bNF0='),
      dc('TlBVIOmXtCBEMkQg5Y+M5ZCR5bim5a69IDc4NCBHQi9z77yM5Y2V6Lez5pe25bu2IDIwMG5zIFsyXQ=='),
      dc('54K55Ye76K6h566X6IqC54K55Y+v5LiL6ZK75p+l55yL5YiA54mH5YaF6YOo'),
    ],
  },
  switchRack: {
    title: dc('54G16KGi5oC757q/5p+c77yITDIg5Lqk5o2iIMK3IOmjjuWGt++8iQ=='),
    lines: [
      dc('NCDmn5zlhbHmib/ovb0gTDIgVUIg5Lqk5o2i77yaNyDlubPpnaIgw5cgMTYg6aKXID0gMTEyIOmil+iKr+eJhyBbMV0='),
      dc('57qmIDU2IOWPsOeBteihouaAu+e6v+iuvuWkh++8iOavj+afnCB+MTQg5Y+w77yM6L2s6L295Y+j5b6E77yJWzRd'),
      dc('5q+P6aKXIEwyIOiKr+eJhyA0OCDDlyAyOCBHQi9zIOerr+WPo++8jDE6MSDml6DmlLbmlZvpnZ7pmLvloZ4gWzFdWzJd'),
      dc('6Leo6IqC54K55bim5a696KGw5YePIDwgMyXvvIzml7blu7blop7liqAgPCAxIM68cyBbMV0='),
      dc('5bGV5Ye65paw5LiA5Luj5b2i5oCB77yaVW5pZmllZEJ1cyBMaW5rRGV2aWNlIMK3IDEyOMOXODAwR0Ug5YWo5YWJIFs2XQ=='),
    ],
  },
  node: {
    title: dc('6K6h566X6IqC54K577yI5YiA54mH5oq96LGh6KeG5Zu+77yJ'),
    lines: [
      dc('OMOXIOaYh+iFviA5MTBD77ya5Y+MIGRpZSBTSU8g5LqS6IGU5oiQIEhpQU0g5qih57uE77yMMTI4R0IgSEJNIC8gMy4yVEIvcyBbMV1bMl0='),
      dc('NMOXIOmysum5jyA5MjAgQ1BVIOWFqOe9keeKtiBOVU1BICsgMzLDlyBERFI1IFsxXVszXQ=='),
      dc('N8OXIOeBteihoiBMMSDkuqTmjaLoiq/niYcgPSA3IOS4qiBVQiDlrZDlubPpnaLvvIzmr4/popfkuIrooYwgNDQ4IEdCL3MgWzFd'),
      dc('5Y2VIE5QVSBVQiAzOTIgR0Ivc+OAgUNQVSAxNjAgR0Ivc++8iOWNleWQke+8iVsxXQ=='),
      dc('5YWJ5Y+jIDU2w5c0MDBHIE9TRlAgVUIgKyA4w5c0MDBHIFFTRlAtREQgUm9DRe+8m+aTjuWkqSBEUFUg5o6lIFZQQyBbMV1bM11bNF0='),
      dc('5rOo77ya5p2/5YaF5o6S5biD5Li65oq96LGh56S65oSP77yM6Z2e55yf5a6eIGxheW91dA=='),
    ],
  },
  topology: {
    title: dc('54G16KGi5LqS6IGU5ouT5omR77yI5Lik5bGC5peg6Zi75aGeIENsb3PvvIk='),
    lines: [
      dc('5q+P6IqC54K5IDcg6aKXIEwxIOiKr+eJh+WQhOWxnuS4gOS4quWtkOW5s+mdou+8jOS4iuihjOiHs+WQjOW5s+mdoiBMMiBbMV0='),
      dc('TDIg5bGC77yaNyDlubPpnaIgw5cgMTYg6Iqv54mH77yMTDHihpRMMiDkuIDkuIDmmKDlsITkv53mjIHpnZ7pmLvloZ4gWzFd'),
      dc('TlBV4oaUTlBVIOWunua1i++8muiKgueCueWGhSAxNjcgR0IvcyAvIOi3qOiKgueCuSAxNjQgR0IvcyBbMV0='),
      dc('UkRNQSDlubPpnaLvvIjnuqLomZrnur/vvInvvJo0MDAgR2Jwcy9OUFXvvIzot6jotoXoioLngrkgc2NhbGUtb3V0IFsxXQ=='),
      dc('VlBDIOW5s+mdou+8iOeBsO+8ie+8muaTjuWkqeWNoSA0MDAgR2Jwc++8jOaOpeaVsOaNruS4reW/g+e9kee7nCBbMV0='),
      dc('5oKs5YGc6IqC54K55Y+v6auY5Lqu5YW2IDcg5p2h5LiK6KGM6ZO+6Lev'),
    ],
  },
};

/** Reference citations shown at the bottom of the info panel. */
export const SOURCES: string[] = [
  dc('WzFdIGFyWGl2OjI1MDYuMTI3MDggwrcgU2VydmluZyBMTE1zIG9uIEh1YXdlaSBDbG91ZE1hdHJpeDM4NA=='),
  dc('WzJdIOWNjuS4uiBBdGxhcyA5MDAgQTMgU3VwZXJQb0Qg5Lqn5ZOB6aG1IC8gaGlhc2NlbmQuY29tIOmbhue+pOmhtQ=='),
  dc('WzNdIOWNjuS4uiBBdGxhcyA4MDBUIEEzIOS6p+WTgemhte+8iOWQjOaetuaehOiKgueCueW9ouaAge+8iQ=='),
  dc('WzRdIFNlbWlBbmFseXNpcyDCtyBIdWF3ZWkgQUkgQ2xvdWRNYXRyaXggMzg077yI5Lyw566X5Y+j5b6E77yJ'),
  dc('WzVdIOWNjuS4uiBIQzIwMjUg54G16KGiIDIuMCDlj5HluIPvvIhBdGxhcyA5NTAvOTYwIOi3r+e6v++8iQ=='),
  dc('WzZdIOi2heiKgueCueWxleWHuuWunuaLjeeFp+eJh++8iOeUqOaIt+aPkOS+m++8iQ=='),
];

export const FOOTNOTE = dc('5rOo77ya5py65p+c5aSW5b2i6YeH55So5a6Y5pa5IDIyNTDDlzYwMMOXMTE1MG1t77yb5p+c5YaFL+adv+WGheW4g+WxgOS4uuWfuuS6juWFrOW8gOi1hOaWmeeahOaKveixoeekuuaEj+OAgg==');
